### ISSUE TITLE
Write Description and Sources

### ISSUE THREAD

**Issue by cmgiven** [code-for-dc-edu/dcps-budget#11]
- [ ] Description
- [ ] Sources

**Comment by cmgiven** [comment]
The description should probably include three major points:
1. How the budgeting process works
2. What each of the categories includes
3. How someone can best contribute to the process

Maybe there are other thoughts?

**Comment by cmgiven** [comment]
@OpenMikeDC notes in #22 that description should include:

1) descriptions of all budget categories
2) link to DCPS budget process description
3) link to DCFPI school budget primer

**Comment by OpenMikeDC** [comment]
Chris,
I think I have the git/github interface working well and I've made a few commits tonight against #11 below.But I have not managed to get nodejs/bower/gulp running. There seem to be some issues with the vanillapackaged version of nodejs on Ubuntu and I'll probably have to tear it all out and start over with a PPA.
In any case, am I correct in assuming that gulp post-processes the stuff in the app directory to generate dist?I've been making my changes to index.html in app.

Based on the strangeness in today's delivery from DCPS, I'm holding off on regenerating the data file untilwe get some clarity on the new numbers.
I'll sound off on the main thread too, but I am also not crazy about the colorbar palette. I can see lightening the 2015text, but I'm concerned that de-saturating the color bars for 2015 has two bad effects: it makes some of the 2015colors look similar to those of different categories in 2016 and it makes the 2015 colors harder to reference againstthe legend (which is based on the 2016 palette).
Mike

```
  From: Chris Given <notifications@github.com>
```

 To: code-for-dc-edu/dcps-budget dcps-budget@noreply.github.com 
Cc: Michael Sandfort cute_moniker@yahoo.com 
 Sent: Tuesday, April 14, 2015 7:45 PM
 Subject: Re: [dcps-budget] Write Description and Sources (#11)

Assigned #11 to @OpenMikeDC.—

**Comment by cmgiven** [comment]
Sorry the preprocessing stuff isn't working for you.

Yes, the app directory is the one you want to change. When you're ready, run `git push` so that your new commits are visible to me.

Opening a color palette issue.

**Comment by cmgiven** [comment]
Ah, sorry, totally missed your new commits. Thanks, Mike!

**Comment by OpenMikeDC** [comment]
Descriptions complete. Opening new issue for sourcing only.
