### ISSUE TITLE
Explain what the lines on the graph view mean.

### ISSUE THREAD

**Issue by OpenMikeDC** [code-for-dc-edu/dcps-budget#19]
This addresses a Beth Bacon comment:
Explain what the lines on the “graph” view mean (something like: "Hover over each line to see the total funding amount for each school in that category. The change in funding between FY15 and FY16 is represented by the angle of the line.”)
Note what the total amount (shown when I hover over one of the graph lines) represents - is it total general ed allocation for that particular school?

**Comment by cmgiven** [comment]
I would argue this could be addressed with #16 and #17 and avoid the unclear "angle of the line" stuff.

**Comment by cmgiven** [comment]
Closing this out. Let's direct any additional discussion into #16.
