### ISSUE TITLE
Legend for the SPED, ELL, At Risk, and Income Linked buttons

### ISSUE THREAD

**Issue by OpenMikeDC** [code-for-dc-edu/dcps-budget#21]
The legend at the top of the Table Gen. Ed. view is great. Can we get a legend like that on the SPED, ELL, At Risk, and Income Linked buttons? 
Beth Bacon comment

**Comment by cmgiven** [comment]
No longer needed as these categories no longer have per-student views. Legend for general education has a new item for the "other" categories.
