### ISSUE TITLE
School detail view should also have the previous year's enrollment

### ISSUE THREAD

**Issue by cmgiven** [code-for-dc-edu/dcps-budget#29]
And perhaps the change?

**Comment by OpenMikeDC** [comment]
(partial close) Change from previous year's enrollment now shown at top level. I did not add either the previous year's enrollment or the change to the school view. Data is also available in the CSV to do the piecharts for sped and ell as well as atrisk.

**Comment by cmgiven** [comment]
Closed with #37.
