### ISSUE TITLE
Clarify school name asterisk

### ISSUE THREAD

**Issue by cmgiven** [code-for-dc-edu/dcps-budget#33]
Some schools have an asterisk appended to their name. I don't believe the content contains an explanation for why. @OpenMikeDC?

**Comment by OpenMikeDC** [comment]
Asterisks removed from updated data file. But there appears to be a substantive issue with these two schools' budgets (Stanton and Woodson). In each case, the school's at-risk allocation includes >$100K of centrally-budgeted at-risk funding (not school budget).
